feat: add city, and distance on kilometric expense line card
axelor/axelor-mobile pull request #269
Opened 2023-11-21 09:54 UTC by gca-axelor

RM#72150

2023-11-22 17:06 UTC, vhu-axelor requested changes

2023-11-23 08:10 UTC, lme-axelor commented on packages/apps/hr/src/i18n/en.json
> +
remove space, not needed in translations

2023-11-23 08:10 UTC, lme-axelor commented on packages/apps/hr/src/i18n/fr.json
> +
remove space, not needed in translations

2023-11-23 08:10 UTC, lme-axelor commented on packages/ui/src/components/templates/ObjectCard/ObjectCard.tsx
> +
I'm not sure it's a good idea to move it this way. 
I understand the need of having the hideIf being evaluate as a first thing but the hideIfNull can cause issue with the custom component as displayText and indicatorText are not used. Maybe we can split condition into two parts like this : 

```
  if (item.hideIf) {
      return null;
    }

    if (item.customComponent != null) {
      return React.cloneElement(item.customComponent, {
        key: `${item.displayText} - ${item.order}`,
      });
    }

  if (item.hideIfNull &&
        checkNullString(item.displayText) &&
        checkNullString(item.indicatorText)) {
      return null;
    }
```

2023-11-24 13:26 UTC, vhu-axelor approved these changes

2023-11-27 13:33 UTC, lme-axelor commented
Need to be splited into two commits before merging to go down to version 7.1

2023-11-27 15:01 UTC, merged