feat: add new filed expense in expenseLine form
axelor/axelor-mobile pull request #291
Opened 2023-11-30 13:50 UTC by gca-axelor

RM#72432

2023-12-01 15:05 UTC, vhu-axelor approved these changes
Work well, nice! 🤩

2023-12-01 15:41 UTC, lme-axelor commented on packages/apps/hr/src/features/expenseLineSlice.js
> +        });
is _searchGeneralExpenseLines & _searchKilometricExpenseLines still required if you refresh the complete expense ? I think the lines are refreshing themselves when the expense is updated no ?

2023-12-01 15:41 UTC, lme-axelor commented on packages/apps/hr/src/components/templates/ExpensePicker/ExpensePicker.js
> +});
I think this is not required anymore with V improvements on Picker component

2023-12-01 15:41 UTC, lme-axelor commented on packages/apps/hr/src/components/templates/ExpensePicker/ExpensePicker.js
> +const ExpensePickerAux = ({
Don't we already have a picker with user's draft expenses ? On the popup to link orphan lines to an expense

2023-12-04 10:42 UTC, vhu-axelor requested changes

2023-12-04 16:33 UTC, vhu-axelor approved these changes

2023-12-07 15:48 UTC, lme-axelor commented on packages/apps/hr/src/components/templates/ExpensePicker/ExpensePicker.js
> +const ExpensePicker = ({title, defaultValue, onChange, readonly, required}) => {
Can you name if DraftExpensePicker please

2023-12-07 15:48 UTC, lme-axelor commented on packages/apps/hr/src/features/expenseLineSlice.js
>  import {updateExpense} from './expenseSlice';
Can you merge imports please

2023-12-11 14:15 UTC, vhu-axelor approved these changes

2023-12-12 16:06 UTC, merged