fix: update list when update inventory
axelor/axelor-mobile pull request #301
Opened 2023-12-11 08:23 UTC by gca-axelor

RM#72862

2023-12-12 09:37 UTC, vhu-axelor approved these changes
Good job! 🔥

2023-12-12 12:11 UTC, lme-axelor commented
See ticket for more details but issue is not resolved. I attached an example video

2023-12-14 09:21 UTC, vhu-axelor requested changes

2023-12-14 09:21 UTC, vhu-axelor commented on packages/apps/stock/src/screens/inventories/InventoryLineListScreen.js
> +    [dispatch, inventory],
I think you don't have to change this

2023-12-14 10:25 UTC, vhu-axelor approved these changes

2023-12-14 16:10 UTC, merged