fix: Selection container when content is null
axelor/axelor-mobile pull request #304
Opened 2023-12-11 12:36 UTC by gca-axelor

RM#72919

2023-12-11 12:39 UTC, gca-axelor commented
maybe its a little tricky to test,you can ask me if you want, we can do this together

2023-12-12 10:34 UTC, vhu-axelor requested changes

2023-12-12 10:34 UTC, vhu-axelor commented on packages/ui/src/components/molecules/SelectionContainer/SelectionContainer.tsx
> +  return (
Remove the condition is enough, you don't have to create `displayContent` const

2023-12-14 10:29 UTC, vhu-axelor approved these changes

2023-12-14 15:57 UTC, merged