feat: add Tour details view
axelor/axelor-mobile pull request #435
Opened 2024-02-21 09:14 UTC by gca-axelor

RM#75345

2024-03-04 09:59 UTC, gca-axelor commented
http://75346-preview.cloud-sw1.axelor.io/

2024-03-04 14:24 UTC, vhu-axelor requested changes

2024-03-04 14:24 UTC, vhu-axelor commented on packages/apps/crm/src/api/index.ts
> +} from './tour-api';
Add fetchTourById

2024-03-06 09:22 UTC, vhu-axelor approved these changes
Nice work! 🤩

2024-03-11 09:22 UTC, lme-axelor commented on packages/apps/crm/src/screens/tour/TourListScreen.js
>              salesperson={item.salespersonUser?.fullName}
Only tour prop is needed here

2024-03-11 09:22 UTC, lme-axelor commented on packages/apps/crm/src/components/molecules/TourValidateButton/TourValidateButton.tsx
> +  return (
This button should be visible only if a line is not validated on the tour

2024-03-11 13:42 UTC, vhu-axelor approved these changes

2024-03-11 15:39 UTC, merged