feat: display label when clicking on PieChart
axelor/axelor-mobile pull request #443
Opened 2024-02-27 10:45 UTC by gca-axelor

RM#74471

2024-02-29 15:29 UTC, vhu-axelor approved these changes

2024-03-04 10:21 UTC, lme-axelor commented on packages/ui/src/components/templates/Dashboard/Chart/PieChart.tsx
> +        }}
Design is not compatible with 'pie' chart

2024-03-04 10:21 UTC, lme-axelor commented on packages/ui/src/components/templates/Dashboard/Chart/PieChart.tsx
> +      borderBottomRightRadius: 7,
It could be nice to split this styles 
Maybe by splitting file in different components (for the legend for example or the label)

2024-03-07 09:27 UTC, vhu-axelor requested changes

2024-03-07 09:27 UTC, vhu-axelor commented on packages/ui/src/components/templates/Dashboard/Chart/PieChart/PieChart.tsx
> +  focusOnPress = true,
When `focusOnPress` is false label should not be displayed. Don't forget to remove `paddingTop`

2024-03-07 09:56 UTC, vhu-axelor approved these changes
Nice work! 🤩

2024-03-11 07:46 UTC, merged